### ISSUE TITLE
No GPU's found

### ISSUE THREAD

**Issue by JSRRosenbaum** [sofmeright/VirtualDisplayDriver_Wizard#1]
I love this project! 

I also am a huge AHK nerd. I really appreciate what you've done here. 

WMIC is depecated in latest insider builds of win 11

See: https://superuser.com/questions/1178674/wmic-is-not-recognized-as-an-internal-or-external-command-operable-program-or

It looks like the appropriate new command is: 

Get-WmiObject win32_videocontroller

![image](https://github.com/user-attachments/assets/a79b0b8d-e7d5-4ff3-8fab-8d6f49079979)

**Comment by SoFMeRight** [comment]
Thank you for submitting this issue! I greatly appreciate it! I very am glad that you are liking the app! I also greatly appreciate that you brought the issue to me with advice for resolving it as well. Hahaha I never would have guessed that wmic was End of Life. I was able to investigate and I *think* the issue should be resolved in the update I just pushed. When you get a moment can you check for me that the GPU(s) are generated properly for you now. I suppose I could fire up a VM and throw a preview build in it, but I also don't know which specific build you are on; so its probably better to just have you test it when you can. The command you gave me was a beautiful lead, I was able to get right on track. That final command I ended up with was a little different "Get-CimInstance -ClassName win32_videocontroller | Select-Object -ExpandProperty Name" but the command you gave me got me to the right MS documentations.

I think its really cool that you are also an AutoHotkey user as well! Its really surprising what you can do with it. Its a lot more flexible than one might think! If I had more experience in other languages I dabble in I may have went another route but I am really confident with it and it let me get this all put together in one long night! Impatience the driving factor :D

Again thank you for raising this issue and helping me ensure this will be a decent experience for all users on all versions of Windows :D

**Comment by JSRRosenbaum** [comment]
That fixed it! Thanks for your great work!

![image](https://github.com/user-attachments/assets/f203edbf-952f-4150-b540-f7a0873291f2)
